"""Train baseline and machine learning models for the DS570 house price project.

Expected repo location:
    src/models/train.py

Run from the repository root:
    python src/models/train.py

The script expects the cleaned data generated by src/data/preprocess.py at:
    data/processed/house_sales_cleaned_for_ds570.csv

For convenience, it also works if the file is placed in the current working directory.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Tuple

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer, TransformedTargetRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

RANDOM_STATE = 42

TARGET = "price_try"
LEAKAGE_COLUMNS = {"price_per_m2", "is_model_candidate_pct", "is_model_candidate_domain"}

CATEGORICAL_FEATURES = [
    "seller_type",
    "room_layout",
    "city",
    "district",
    "neighborhood",
]

NUMERIC_FEATURES = [
    "area_m2",
    "rooms",
    "living_rooms",
    "total_rooms",
    "listing_month",
    "listing_day",
]

FEATURES = CATEGORICAL_FEATURES + NUMERIC_FEATURES


def find_project_root() -> Path:
    """Return the most likely project root based on current file location."""
    current = Path(__file__).resolve()
    # If located at repo/src/models/train.py, parents[2] is repo root.
    if len(current.parents) >= 3 and current.parents[1].name == "models":
        return current.parents[2]
    return Path.cwd()


def find_input_path(root: Path) -> Path:
    """Find cleaned dataset in common project locations."""
    candidates = [
        root / "data" / "processed" / "house_sales_cleaned_for_ds570.csv",
        root / "house_sales_cleaned_for_ds570.csv",
        Path("/mnt/data/house_sales_cleaned_for_ds570.csv"),
    ]
    for path in candidates:
        if path.exists():
            return path
    raise FileNotFoundError(
        "Could not find house_sales_cleaned_for_ds570.csv. "
        "Run src/data/preprocess.py first or place the file under data/processed/."
    )


def prepare_data(path: Path) -> pd.DataFrame:
    """Load and filter modeling data."""
    df = pd.read_csv(path, encoding="utf-8-sig")
    df = df.drop_duplicates().copy()

    required = set(FEATURES + [TARGET, "is_model_candidate_domain"])
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    df = df[df["is_model_candidate_domain"].astype(bool)].copy()
    df = df.dropna(subset=[TARGET])
    return df


def split_data(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series]:
    """Create a reproducible train-test split."""
    X = df[FEATURES].copy()
    y = df[TARGET].astype(float).copy()

    # Stratifying by city keeps geographic composition more stable in train/test.
    stratify = df["city"] if df["city"].nunique() > 1 else None
    return train_test_split(
        X,
        y,
        test_size=0.20,
        random_state=RANDOM_STATE,
        stratify=stratify,
    )


def predict_city_district_median(
    train_x: pd.DataFrame,
    train_y: pd.Series,
    test_x: pd.DataFrame,
) -> np.ndarray:
    """Baseline predictor using city+district median with city/global fallbacks."""
    train = train_x.copy()
    train[TARGET] = train_y.values

    district_median = train.groupby(["city", "district"])[TARGET].median()
    city_median = train.groupby("city")[TARGET].median()
    global_median = float(train_y.median())

    preds: List[float] = []
    for _, row in test_x.iterrows():
        key = (row["city"], row["district"])
        if key in district_median.index:
            preds.append(float(district_median.loc[key]))
        elif row["city"] in city_median.index:
            preds.append(float(city_median.loc[row["city"]]))
        else:
            preds.append(global_median)
    return np.asarray(preds)


def build_model() -> TransformedTargetRegressor:
    """Build a leakage-safe sklearn pipeline."""
    numeric_pipeline = Pipeline(
        steps=[("imputer", SimpleImputer(strategy="median"))]
    )

    categorical_pipeline = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", min_frequency=5)),
        ]
    )

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_pipeline, NUMERIC_FEATURES),
            ("cat", categorical_pipeline, CATEGORICAL_FEATURES),
        ],
        remainder="drop",
    )

    regressor = RandomForestRegressor(
        n_estimators=250,
        max_depth=18,
        min_samples_leaf=2,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

    pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("model", regressor),
        ]
    )

    # House prices are strongly right-skewed, so the model learns log(price)
    # and predictions are transformed back to TRY.
    return TransformedTargetRegressor(
        regressor=pipeline,
        func=np.log1p,
        inverse_func=np.expm1,
        check_inverse=False,
    )


def calculate_metrics(y_true: pd.Series, y_pred: np.ndarray) -> Dict[str, float]:
    """Return regression metrics in interpretable units."""
    y_true_arr = np.asarray(y_true, dtype=float)
    y_pred_arr = np.asarray(y_pred, dtype=float)
    mae = mean_absolute_error(y_true_arr, y_pred_arr)
    rmse = float(np.sqrt(mean_squared_error(y_true_arr, y_pred_arr)))
    r2 = r2_score(y_true_arr, y_pred_arr)
    mape = float(np.mean(np.abs((y_true_arr - y_pred_arr) / y_true_arr)) * 100)
    smape = float(
        np.mean(
            2 * np.abs(y_pred_arr - y_true_arr) /
            (np.abs(y_true_arr) + np.abs(y_pred_arr))
        ) * 100
    )
    return {
        "MAE_TRY": float(mae),
        "RMSE_TRY": float(rmse),
        "R2": float(r2),
        "MAPE_percent": float(mape),
        "SMAPE_percent": float(smape),
    }


def aggregate_feature_importance(model: TransformedTargetRegressor) -> pd.DataFrame:
    """Aggregate one-hot feature importances back to original input columns."""
    fitted_pipeline = model.regressor_
    rf = fitted_pipeline.named_steps["model"]
    preprocessor = fitted_pipeline.named_steps["preprocessor"]

    output_names = preprocessor.get_feature_names_out()
    importances = rf.feature_importances_

    rows = []
    for output_name, importance in zip(output_names, importances):
        if output_name.startswith("num__"):
            original = output_name.replace("num__", "")
        elif output_name.startswith("cat__"):
            remainder = output_name.replace("cat__", "")
            original = next(
                (col for col in CATEGORICAL_FEATURES if remainder.startswith(col + "_")),
                remainder,
            )
        else:
            original = output_name
        rows.append({"feature": original, "importance": float(importance)})

    importance_df = pd.DataFrame(rows)
    return (
        importance_df.groupby("feature", as_index=False)["importance"]
        .sum()
        .sort_values("importance", ascending=False)
    )


def main() -> None:
    root = find_project_root()
    input_path = find_input_path(root)

    output_dir = root / "models"
    reports_dir = root / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)

    df = prepare_data(input_path)
    X_train, X_test, y_train, y_test = split_data(df)

    baseline_pred = predict_city_district_median(X_train, y_train, X_test)
    baseline_metrics = calculate_metrics(y_test, baseline_pred)

    model = build_model()
    model.fit(X_train, y_train)
    model_pred = model.predict(X_test)
    model_pred = np.maximum(model_pred, 0)
    model_metrics = calculate_metrics(y_test, model_pred)

    metrics = {
        "dataset": {
            "input_path": str(input_path),
            "rows_after_filtering": int(len(df)),
            "train_rows": int(len(X_train)),
            "test_rows": int(len(X_test)),
            "target": TARGET,
            "excluded_leakage_columns": sorted(LEAKAGE_COLUMNS),
        },
        "features": {
            "categorical": CATEGORICAL_FEATURES,
            "numeric": NUMERIC_FEATURES,
        },
        "baseline_city_district_median": baseline_metrics,
        "random_forest_log_target": model_metrics,
    }

    predictions = X_test.copy()
    predictions["actual_price_try"] = y_test.values
    predictions["baseline_prediction_try"] = baseline_pred
    predictions["ml_prediction_try"] = model_pred
    predictions["absolute_error_try"] = np.abs(predictions["actual_price_try"] - predictions["ml_prediction_try"])

    feature_importance = aggregate_feature_importance(model)

    joblib.dump(model, output_dir / "house_price_model.joblib")
    predictions.to_csv(reports_dir / "test_predictions.csv", index=False, encoding="utf-8-sig")
    feature_importance.to_csv(reports_dir / "feature_importance.csv", index=False, encoding="utf-8-sig")

    with open(reports_dir / "metrics.json", "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2, ensure_ascii=False)

    print(json.dumps(metrics, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()

